### ISSUE TITLE
When a revolt user replies to a user on discord, it shows up as unknown#0000

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [janderedev/automod#12]
![image](https://user-images.githubusercontent.com/76877633/166165661-4f7061ab-a19e-4763-8284-6d8ca7fd5984.png)
![image](https://user-images.githubusercontent.com/76877633/166165695-cc0955cd-4ec0-40a3-aab7-c30e894e3475.png)

**Comment by sussycatgirl** [comment]
I *think* this should be fixed in 21315f490b6e09e67fadd78a49c4732cd3bce19c, but I can't currently deploy AutoMod until Revolt itself is updated as I already adapted the bot to the upcoming API changes.

The bug where messages from Discord duplicate on the Revolt side has been confirmed to be an issue with Revolts API.

I'll leave this open as I'm not 100% sure that it's fully fixed.
