### ISSUE TITLE
request: redis port docker compose variable

### ISSUE THREAD

**Issue by avasilic** [janderedev/automod#32]
Hi there, 

The docker image currently starts `eqalpha/keydb` for Redis. Could we get a env or docker-compose file option to use a different port?

**Comment by sussycatgirl** [comment]
You should be able to edit the compose file to add this to the keydb service:

```yml
    ports:
      - 12345:6379
```

Which makes it listen on port 12345 externally. Alternatively, if you want to use another redis server instead of the one in the compose, you should be able to set REDIS_URL in .env and delete the redis section from the compose file entirely.

By default, redis doesn't listen on any port externally and only containers in the same stack can connect to it, but if you do what I described above you should make it require authentication. I don't remember how to do that though
